dist: xenial
language: python
python:
    - "3.7"

matrix:
  fast_finish: true

install:
  - pip install pipenv
  - pipenv install

script:
    - pipenv run pylama
    - python -m unittest discover tests/

notifications:
  email: false
