dist: xenial
language: python
python:
  - "3.7"

matrix:
  fast_finish: true

install:
  - pip install pipenv --upgrade
  - pipenv sync
  - pipenv sync --dev

script:
  - pipenv run pylint **/*.py
  - pipenv run mypy **/*.py
  - pipenv run pytest

notifications:
  email: false
