sudo: required
language: python

matrix:
  fast_finish: true

install:
  - pip install pipenv --upgrade
  - pipenv install

script:
  - pipenv run pylama
  - pipenv run pytest

notifications:
  email: false
