dist: xenial
language: python
python:
  - "3.7"

matrix:
  fast_finish: true

install:
  - pip install pipenv --upgrade
  - pipenv sync
  - pipenv sync --dev

script:
  - pipenv run pylint garfield_downloader tests
  - pipenv run mypy --ignore-missing-imports garfield_downloader tests
  - pipenv run pytest

notifications:
  email: false
