dist: xenial
language: python
python:
  - "3.7"

matrix:
  fast_finish: true

install:
  - pip install pipenv
  - pipenv install

before_script:
  - pipenv shell

script:
  - pipenv run pylama
  - pipenv run pytest

notifications:
  email: false
