language: python

matrix:
  fast_finish: true

install:
  - pip install pipenv
  - pipenv install

script:
    - pipenv check
    - pylama
    - python -m unittest discover tests/

notifications:
  email: false
