dist: xenial
language: python
python:
  - "3.7"

matrix:
  fast_finish: true

install:
  - pip install pipenv --upgrade
  - pip install codecov
  - pipenv sync
  - pipenv sync --dev

script:
  - pipenv run pylint garfield_downloader tests
  - pipenv run mypy --ignore-missing-imports garfield_downloader tests
  - pipenv run pytest --cov --cov-report=xml

after_success:
  - codecov -t $TOKEN

notifications:
  email: false
